backend:
  name: git-gateway
  repo: joayo13/test-astro-decap
  branch: main
local_backend: true
media_folder: src/assets/img
public_folder: src/assets/img

collections:
  - name: "index"
    label: "Index Page"
    files:
      - label: "Homepage Content"
        name: "index"
        file: "src/content/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Paragraph", name: "paragraph", widget: "text" }