backend:
  name: git-gateway
  repo: joayo13/test-astro-decap
  branch: main
local_backend: true
media_folder: src/assets/img
public_folder: src/assets/img

collections:
  - name: "index"
    label: "Index Page"
    files:
      - label: "Title Content"
        name: "title"
        file: "src/content/index/title.md"
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"

      - label: "Introduction Content"
        name: "introduction"
        file: "src/content/index/introduction.md"
        fields:
          - label: "Introduction Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
